[package]

name    = "sdl2"
description = "SDL2 bindings for Rust"
repository = "https://github.com/AngryLawyer/rust-sdl2"
documentation = "http://angrylawyer.github.io/rust-sdl2/sdl2/"
version = "0.30.0"
license = "MIT"
authors = [ "Tony Aldridge <tony@angry-lawyer.com>", "Cobrand <cobrandw@gmail.com>"]
keywords = ["SDL", "windowing", "graphics", "api"]
categories = ["rendering","games","api-bindings","game-engines","multimedia"]

[lib]

name       = "sdl2"
path       = "src/sdl2/lib.rs"

[dependencies]
bitflags = "0.7"
libc = "0.2"
rand = "0.3"
lazy_static="0.2"

[dependencies.num]
version = "0.1"
default-features = false

[dependencies.sdl2-sys]
path = "sdl2-sys"
version = "0.30.0"

[dependencies.c_vec]
version = "1.0.*"
optional = true

[features]

unsafe_textures = []
default = []
ttf = []
image = []
gfx = ["c_vec"]
mixer = []

use-pkgconfig = [ "sdl2-sys/use-pkgconfig" ]
use_mac_framework = ["sdl2-sys/use_mac_framework"]

[[example]]
name = "animation"

[[example]]
name = "audio-queue-squarewave"

[[example]]
name = "audio-wav"

[[example]]
name = "audio-whitenoise"

[[example]]
name = "demo"

[[example]]
name = "game-controller"

[[example]]
required-features = ["unsafe_textures"]
name = "game-of-life-unsafe-textures"

[[example]]
name = "game-of-life"

[[example]]
required-features = ["gfx"]
name = "gfx-demo"

[[example]]
name = "haptic"

[[example]]
required-features = ["image"]
name = "image-demo"

[[example]]
name = "joystick"

[[example]]
name = "keyboard-state"

[[example]]
name = "message-box"

[[example]]
required-features = ["mixer"]
name = "mixer-demo"

[[example]]
name = "mouse-state"

[[example]]
name = "no-renderer"

[[example]]
name = "relative-mouse-state"

[[example]]
name = "renderer-target"

[[example]]
name = "renderer-texture"

[[example]]
name = "renderer-yuv"

[[example]]
name = "resource-manager"

[[example]]
required-features = ["ttf"]
name = "ttf-demo"

[[example]]
name = "window-properties"
