[package]

name    = "sdl2"
description = "SDL2 bindings for Rust"
repository = "https://github.com/AngryLawyer/rust-sdl2"
version = "0.0.16"
license = "MIT"
authors = [ "Tony Aldridge <tony@angry-lawyer.com>" ]
keywords = ["SDL", "windowing", "graphics"]

[lib]

name       = "sdl2"
path       = "src/sdl2/lib.rs"

[features]

image = ["sdl2_image"]

[dependencies.sdl2-sys]

path = "sdl2-sys"
version = "0.0.16"

[dependencies.sdl2_image]

optional = true
path = "sdl2_image"
