[package]

name = "sdl2-sys"
description = "Raw SDL2 bindings for Rust, used internally rust-sdl2"
repository = "https://github.com/AngryLawyer/rust-sdl2"
version = "0.31.0"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]
keywords = ["SDL", "windowing", "graphics", "ffi"]
categories = ["rendering","games","external-ffi-bindings","game-engines","multimedia"]
license = "MIT"
links = "SDL2"
build = "build.rs"

[lib]
name = "sdl2_sys"
path = "src/lib.rs"

[build-dependencies.bindgen]
version = "0.35"
optional = true

[build-dependencies.pkg-config]
version = "0.3.9"
optional = true

[build-dependencies.cmake]
version = "0.1"
optional = true

[build-dependencies.reqwest]
version = "0.7"
optional = true

[build-dependencies.tar]
version = "0.4"
optional = true

[build-dependencies.flate2]
version = "0.2"
optional = true

[build-dependencies]
cfg-if = "0.1"

[features]

default = []
use-pkgconfig = ["pkg-config"]
use-bindgen = ["bindgen"]
static-link = []
use_mac_framework = []
bundled = ["cmake", "reqwest", "tar", "flate2"]
mixer = []
image = []
ttf = []
gfx = []
